"""Initial migration

Revision ID: d66971bf3dd7
Revises: 
Create Date: 2026-03-07 09:57:26.796519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66971bf3dd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_topic_id'), 'claims', ['topic_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('REGULATORY', 'CLINICAL', 'CORPORATE', 'PATENT', 'MEDIA', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('evidence_strength', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='evidencestrength'), nullable=False),
    sa.Column('extracted_summary', sa.Text(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_strength'), 'evidence', ['evidence_strength'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    op.create_table('user_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'UNSURE', 'REJECT', name='decision'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=False),
    sa.Column('reason_tag', sa.String(), nullable=True),
    sa.Column('warning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_judgments_claim_id'), 'user_judgments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_user_judgments_id'), 'user_judgments', ['id'], unique=False)
    op.create_index(op.f('ix_user_judgments_user_id'), 'user_judgments', ['user_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='queuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_judgment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_judgment_id'], ['user_judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_claim_id'), 'review_queue', ['claim_id'], unique=False)
    op.create_index(op.f('ix_review_queue_id'), 'review_queue', ['id'], unique=False)
    op.create_index(op.f('ix_review_queue_review_date'), 'review_queue', ['review_date'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_index(op.f('ix_review_queue_user_id'), 'review_queue', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_user_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_review_date'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_claim_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_user_judgments_user_id'), table_name='user_judgments')
    op.drop_index(op.f('ix_user_judgments_id'), table_name='user_judgments')
    op.drop_index(op.f('ix_user_judgments_claim_id'), table_name='user_judgments')
    op.drop_table('user_judgments')
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_strength'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claims_topic_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.execute("DROP TYPE IF EXISTS sourcetype, evidencestrength, decision, confidence, queuestatus")
    # ### end Alembic commands ###
